version: "3.8"

services:
  web:
    build: .
    container_name: surf_ai
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"   # Your Flask app
      - "5901:5901"   # VNC
      - "6901:6901"   # noVNC
    privileged: true
    volumes:
      - .:/app

